name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_gem:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true
        
    - name: Run tests
      run: |
        bundle exec rspec spec/unit/lib/temporal/configuration_spec.rb
