name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test_gem:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - uses: actions/checkout@v3

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0.3
        bundler-cache: true

    - name: Run tests
      run: |
        bundle exec rspec

  test_examples:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
      - uses: actions/checkout@v3

      - name: Start containerized server and dependencies
        run: |
          docker-compose \
            -f examples/docker-compose.yml \
            up -d

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3

      - name: Bundle Install
        run: |
          cd examples && bundle install --path vendor/bundle

      - name: Wait for containers to settle
        run: |
          sleep 15

      - name: Register Namespace
        run: |
          cd examples && bin/register_namespace ruby-samples

      - name: Boot up worker
        run: |
          cd examples && bin/worker &

      - name: Boot up crypt worker
        env:
          USE_ENCRYPTION: 1
        run: |
          cd examples && bin/worker &

      - name: Boot up worker for v2 error serialization tests
        env:
          USE_ERROR_SERIALIZATION_V2: 1
        run: |
          cd examples && bin/worker &
